oxc_image: xcode8
language: objective-c
script:
    - xcodebuild -scheme 'DeviceLayout-iOS' -sdk iphonesimulator CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO test | xcpretty -c
    - xcodebuild -scheme 'DeviceLayout-OSX' test | xcpretty -c
